"""fix(app.model):correction in the relationship with the school_subjects and library tables

Revision ID: 38a0f4d102ed
Revises: acb4c451115f
Create Date: 2022-03-04 12:45:58.030368

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '38a0f4d102ed'
down_revision = 'acb4c451115f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absence', sa.Column('justify', sa.Boolean(), nullable=True))
    op.drop_column('absence', 'justtify')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('absence', sa.Column('justtify', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('absence', 'justify')
    # ### end Alembic commands ###
