"""create tables

Revision ID: 456e6f4a021c
Revises: b00c35cdbdda
Create Date: 2022-03-02 15:24:28.133828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '456e6f4a021c'
down_revision = 'b00c35cdbdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'book_id',
               existing_type=sa.VARCHAR(),
               type_=postgresql.UUID(as_uuid=True),
               existing_nullable=False)
    op.alter_column('employees', 'employee_id',
               existing_type=sa.VARCHAR(),
               type_=postgresql.UUID(as_uuid=True),
               existing_nullable=False)
    op.alter_column('library', 'library_id',
               existing_type=sa.VARCHAR(),
               type_=postgresql.UUID(as_uuid=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library', 'library_id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('employees', 'employee_id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('books', 'book_id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
