"""feat:created grades models

Revision ID: 66a8fa0ccc84
Revises: f2c30558453a
Create Date: 2022-03-02 16:15:36.667155

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66a8fa0ccc84'
down_revision = 'f2c30558453a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('grade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ativity', sa.String(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('grade_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    # ### end Alembic commands ###
