"""feat:created absence models

Revision ID: 731c637c2807
Revises: f2c30558453a
Create Date: 2022-03-02 16:20:13.028155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '731c637c2807'
down_revision = 'f2c30558453a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence',
    sa.Column('absence_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('justtify', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('absence_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('absence')
    # ### end Alembic commands ###
