"""refactor(classroom_model): alteraçao nome e nas configuraçoes da coluna classroom_id

Revision ID: a60d6297b449
Revises: 
Create Date: 2022-03-02 15:25:43.471438

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a60d6297b449'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_model',
    sa.Column('classroom_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('classroom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_model')
    # ### end Alembic commands ###
