"""created table library

Revision ID: a87d06572468
Revises: 
Create Date: 2022-03-02 14:40:10.705578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87d06572468'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('library_id', sa.String(), nullable=False),
    sa.Column('date_withdrawal', sa.Date(), nullable=False),
    sa.Column('date_return', sa.Date(), nullable=True),
    sa.Column('date_accurancy', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('library_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library')
    # ### end Alembic commands ###
