"""feat(app.models.school_subjects_model): create table SchoolSubjectsModels

Revision ID: d5af10d026dd
Revises: 
Create Date: 2022-03-02 13:13:23.413655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5af10d026dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_subjects_model',
    sa.Column('school_subject_id', sa.Integer(), nullable=False),
    sa.Column('school_subject', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('school_subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_subjects_model')
    # ### end Alembic commands ###
