"""refactor(app.school_subject_model):change in table import method and school_subject_id column configuration

Revision ID: ff4ebc3ff425
Revises: 
Create Date: 2022-03-02 15:41:59.056774

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff4ebc3ff425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_subjects_model',
    sa.Column('school_subject_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('school_subject', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('school_subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_subjects_model')
    # ### end Alembic commands ###
